### ISSUE TITLE
CoreParser : An exception occurred while parsing the file: System.FormatException, Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

### ISSUE THREAD

**Issue by kd7uiy** [Visual-Stylecop/Visual-StyleCop#83]
Received the following error. The file it is trying to parse is https://github.com/TeamPorcupine/ProjectPorcupine/blob/master/Assets/Scripts/Models/Prototypes/PrototypeMap.cs eab9987, submitted around September 11

```
Warning     SA0001 : CoreParser : An exception occurred while parsing the file: System.FormatException, Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at StyleCop.StyleCopThread.RunAnalyzers(CodeDocument document, SourceParser parser, IEnumerable`1 analyzers)
   at StyleCop.StyleCopThread.TestAndRunAnalyzers(CodeDocument document, SourceParser parser, IEnumerable`1 analyzers, Int32 passNumber)
   at StyleCop.StyleCopThread.ParseAndAnalyzeDocument(SourceCode sourceCode, DocumentAnalysisStatus documentStatus)
   at StyleCop.StyleCopThread.DoWork(Object sender).    ProjectPorcupine.CSharp C:\Users\Ben Pearson\Documents\Unity\ProjectPorcupine\Assets\Scripts\Models\Prototypes\PrototypeMap.cs  1   
```

**Comment by kd7uiy** [comment]
Note that the warning went away with https://github.com/TeamPorcupine/ProjectPorcupine/pull/1336, which simply removed a space after `this` in this function:

```
    public T this [int index]
    {
        get
        {
            return prototypes.ElementAt(index).Value;
        }
    }
```
